//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE.Model.Shared {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPE.Model.Shared.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理员{0} ”{1}“ 不能删除。 的本地化字符串。
        /// </summary>
        internal static string AdministratorCannotDelete {
            get {
                return ResourceManager.GetString("AdministratorCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理员 ”{0}“ 不能修改账号。 的本地化字符串。
        /// </summary>
        internal static string AdministratorCannotModifyUserName {
            get {
                return ResourceManager.GetString("AdministratorCannotModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 已经删除。 的本地化字符串。
        /// </summary>
        internal static string AlreadyDeleteError {
            get {
                return ResourceManager.GetString("AlreadyDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不能为空。 的本地化字符串。
        /// </summary>
        internal static string CannotNullError {
            get {
                return ResourceManager.GetString("CannotNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 已经存在。 的本地化字符串。
        /// </summary>
        internal static string DuplicateError {
            get {
                return ResourceManager.GetString("DuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel {0} 列数不正确。 的本地化字符串。
        /// </summary>
        internal static string ExcelColumnCountError {
            get {
                return ResourceManager.GetString("ExcelColumnCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel 表 {0} 不存在。 的本地化字符串。
        /// </summary>
        internal static string ExcelSheetNameNotExists {
            get {
                return ResourceManager.GetString("ExcelSheetNameNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel表 {0} {1} 表对无效。 的本地化字符串。
        /// </summary>
        internal static string ExcelSheetTitleInvalid {
            get {
                return ResourceManager.GetString("ExcelSheetTitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 {0} 不存在。 的本地化字符串。
        /// </summary>
        internal static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不能为空或空白。 的本地化字符串。
        /// </summary>
        internal static string InvalidError {
            get {
                return ResourceManager.GetString("InvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 未删除。 的本地化字符串。
        /// </summary>
        internal static string NotDeleteError {
            get {
                return ResourceManager.GetString("NotDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不存在。 的本地化字符串。
        /// </summary>
        internal static string NotExistsError {
            get {
                return ResourceManager.GetString("NotExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 {0} 不能删除。 的本地化字符串。
        /// </summary>
        internal static string RoleCannotDelete {
            get {
                return ResourceManager.GetString("RoleCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 {0} 未删除。 的本地化字符串。
        /// </summary>
        internal static string RoleNotDeleted {
            get {
                return ResourceManager.GetString("RoleNotDeleted", resourceCulture);
            }
        }
    }
}
