/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FooterLayout: typeof import('./src/components/Layouts/FooterLayout.vue')['default']
    GroupInput: typeof import('./src/components/forms/GroupInput.vue')['default']
    HeaderLayout: typeof import('./src/components/Layouts/HeaderLayout.vue')['default']
    HomeComponent: typeof import('./src/components/HomeComponent.vue')['default']
    InputRow: typeof import('./src/components/forms/InputRow.vue')['default']
    LoginComponent: typeof import('./src/components/account/LoginComponent.vue')['default']
    LoginPartial: typeof import('./src/components/Layouts/LoginPartial.vue')['default']
    MainLayout: typeof import('./src/components/Layouts/MainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
